export const NexuApenasSemFundoLogo = require('../../public/NexuApenasSemFundo.png')
export const NexuApenasSemFundoPretaLogo = require('../../public/NexuApenasSemFundoPreta.png')
export const NexuApenasLogo = require('../../public/NexuApenas.png')
export const NexuLogo = require('../../public/Nexu.png')
export const NexuSemFundoLogo = require('../../public/NexuSemFundo.png')
